sudo: required
language: perl6
perl6:
    - latest
cache:
    directories
    - $HOME/Net-IP-Lite-Perl6
before_install:
    - git clone https://github.com/tbrowder/Net-IP-Lite-Perl6.git $HOME

install:
    - rakudobrew build-panda
    - panda install ./Net-IP-Lite-Perl6
    - panda installdeps .
