sudo: false
language: perl6
perl6:
    - latest
install:
    - rakudobrew build-panda
    - panda install zef
    - git clone https://github.com/tbrowder/Net-IP-Lite-Perl6.git
    - zef installdeps .
